// lib/features/driver/activity/activityEvents.ts
export const DRIVER_EVENTS = [
  'DRIVER_ROUTE_STARTED',
  'DRIVER_STOP_APPROACHED',
  'DRIVER_STOP_ARRIVED',
  'DRIVER_PICKUP_CONFIRMED',
  'DRIVER_PICKUP_SKIPPED',
  'DRIVER_PICKUP_FAILED',
  'DRIVER_DEVIATED',
  'DRIVER_REJOINED_ROUTE',
  'DRIVER_FEEDBACK_SUBMITTED',
  'DRIVER_LOCATION_CORRECTED',
  'DRIVER_ROUTE_COMPLETED',
  'DRIVER_ROUTE_PAUSED',
  'DRIVER_ROUTE_RESUMED',
] as const;

export type DriverEventType = typeof DRIVER_EVENTS[number];