// lib/core/field-intelligence/events/fieldEventTypes.ts
export const FIELD_INTERNAL_EVENTS = {
  RAW_EVENT_RECORDED: 'FIELD_RAW_EVENT_RECORDED',
  OBSERVATION_RECORDED: 'FIELD_OBSERVATION_RECORDED',
  SIGNAL_PRODUCED: 'FIELD_SIGNAL_PRODUCED',
  CORRECTION_PROPOSED: 'FIELD_CORRECTION_PROPOSED',
  CORRECTION_APPLIED: 'FIELD_CORRECTION_APPLIED',
  INTELLIGENCE_UPDATED: 'FIELD_INTELLIGENCE_UPDATED',
} as const;

export type FieldInternalEvent = typeof FIELD_INTERNAL_EVENTS[keyof typeof FIELD_INTERNAL_EVENTS];