// lib/core/communications/events/authEvents.ts
export const AUTH_EMAIL_EVENTS = {
  AUTH_OTP_REQUESTED: 'AUTH_OTP_REQUESTED',
  AUTH_EMAIL_VERIFICATION_REQUESTED: 'AUTH_EMAIL_VERIFICATION_REQUESTED',
  AUTH_PASSWORD_RESET_REQUESTED: 'AUTH_PASSWORD_RESET_REQUESTED',
  AUTH_ACCOUNT_RECOVERY_REQUESTED: 'AUTH_ACCOUNT_RECOVERY_REQUESTED',
  AUTH_2FA_ENROLLED: 'AUTH_2FA_ENROLLED',
  AUTH_NEW_LOGIN: 'AUTH_NEW_LOGIN',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_SECURITY_ALERT: 'AUTH_SECURITY_ALERT',
} as const;