// lib/core/communications/events/emailEvents.ts
export const EMAIL_EVENTS = {
  // Auth
  AUTH_DRIVER_CREDENTIALS_SENT: 'AUTH_DRIVER_CREDENTIALS_SENT',
  AUTH_WELCOME_SENT: 'AUTH_WELCOME_SENT',
  AUTH_OTP_REQUESTED: 'AUTH_OTP_REQUESTED',
  AUTH_EMAIL_VERIFICATION_REQUESTED: 'AUTH_EMAIL_VERIFICATION_REQUESTED',
  AUTH_PASSWORD_RESET_REQUESTED: 'AUTH_PASSWORD_RESET_REQUESTED',
  AUTH_ACCOUNT_RECOVERY_REQUESTED: 'AUTH_ACCOUNT_RECOVERY_REQUESTED',
  AUTH_2FA_ENROLLED: 'AUTH_2FA_ENROLLED',
  AUTH_SECURITY_ALERT: 'AUTH_SECURITY_ALERT',

  // Billing
  BILLING_INVOICE_CREATED: 'BILLING_INVOICE_CREATED',
  BILLING_PAYMENT_RECEIVED: 'BILLING_PAYMENT_RECEIVED',
  BILLING_REMINDER_DUE: 'BILLING_REMINDER_DUE',

  // Operations
  OPS_ROUTE_ASSIGNED: 'OPS_ROUTE_ASSIGNED',
  OPS_PICKUP_COMPLETED: 'OPS_PICKUP_COMPLETED',
  OPS_INCIDENT_REPORTED: 'OPS_INCIDENT_REPORTED',
} as const;

export type EmailEvent = typeof EMAIL_EVENTS[keyof typeof EMAIL_EVENTS];